### ISSUE TITLE
Recognize, connect, then turn unavailable

### ISSUE THREAD

**Issue by thomasmandrews** [wez/govee-lan-hass#13]
I followed all of steps and HA recognized my devices but then the second I clicked on one of the devices to change state everything became unavailable without a command being successful.

**Comment by wez** [comment]
Please run through https://github.com/wez/govee-lan-hass#troubleshooting and share the logs and state that you collect

**Comment by piedrola** [comment]
Hi Wez, I will use this thread as it is the same problem that I have. I have 30 Govee Lights connect via LAN API and your plugin. About 25 of them work perfect. There are just some that don't work. 
To make them work again I restart the plugin, then the lights will get recognized and directly afterwards they become unavailable. 

I restartet the network, I flushed my DHCP. As my HA is very new I even set up a whole new system just to make sure that it is not some sort of caching error. And of course I have reset the govee devices several times and tried to disable/enable LAN API control. I have the problem since about 5 weeks, the lights have never been working correctly. I waited to open an issue here because I read that it can take time that everything works.

Is there anything you know about that problem? 

My log is very full because of the 30 devices, but I took time to search for the important things. 

> 2023-05-11 17:19:41.609 DEBUG (MainThread) [custom_components.govee_lan.light] device state updated: 14:C4:32:38:31:46:5A:FF entity_id=None --> None {'device_id': '14:C4:32:38:31:46:5A:FF', 'model': 'H61A5', 'http_definition': GoveeHttpDeviceDefinition(device_id='14:C4:32:38:31:46:5A:FF', model='H61A5', device_name='RGB web1 2', controllable=True, retrievable=True, supported_commands=['turn', 'brightness', 'color', 'colorTem'], properties={'colorTem': {'range': {'min': 2000, 'max': 9000}}})}
2023-05-11 17:19:41.609 INFO (MainThread) [custom_components.govee_lan.light] Adding 14:C4:32:38:31:46:5A:FF RGB web1 2

> 2023-05-11 17:19:42.044 DEBUG (MainThread) [custom_components.govee_lan.light] device state updated: 14:C4:32:38:31:46:5A:FF entity_id=light.rgb_web1_2 --> None {'device_id': '14:C4:32:38:31:46:5A:FF', 'model': 'H61A5', 'http_definition': GoveeHttpDeviceDefinition(device_id='14:C4:32:38:31:46:5A:FF', model='H61A5', device_name='RGB web1 2', controllable=True, retrievable=True, supported_commands=['turn', 'brightness', 'color', 'colorTem'], properties={'colorTem': {'range': {'min': 2000, 'max': 9000}}}), 'lan_definition': GoveeLanDeviceDefinition(ip_addr='10.10.21.155', device_id='14:C4:32:38:31:46:5A:FF', model='H61A5', ble_hardware_version='3.01.10', ble_software_version='3.03.21', wifi_hardware_version='1.02.00', wifi_software_version='2.05.01')}

> 2023-05-11 17:21:53.987 DEBUG (MainThread) [custom_components.govee_lan.light] async_update will poll 14:C4:32:38:31:46:5A:FF light.rgb_web1_2
2023-05-11 17:21:56.995 DEBUG (MainThread) [custom_components.govee_lan.light] timeout while querying device state for 14:C4:32:38:31:46:5A:FF light.rgb_web1_2
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/govee_lan/light.py", line 420, in async_update
await self._govee_controller.update_device_state(self._govee_device)
File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 287, in update_device_state
await asyncio.wait_for(future, timeout=self.device_control_timeout)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError


Any idea how to fix this? 
Thank you anyway for a great working plugin. I'm able to see that my problem isn't some sort of bug in your plugin, there seems to be another problem that is related to your plugin at least. Maybe you can help! 

Daniél

**Comment by wez** [comment]
The error indicates that the device is not responding to the LAN request within the configured timeout.

Is there some commonality between the devices that don't respond? Are they the same model, but different from the rest of the lights you own?

I noticed while I was building this that sending too many commands within a short period could result in the device not responding to the LAN API commands. Is something like that happening for you? eg: is there some automation you have that might be swamping those devices?

**Comment by piedrola** [comment]
Hey Wez, thanks for your answer. Indeed there is something in common. All unworking devices are H61A5. 
They are no other commands send than by your plugin. No automations, no other apps. 

Any idea if this could be correlated to your plugin? Govee states that this device is supported.

Thanks
Daniél

**Comment by wez** [comment]
You'll need to change the code for that:

https://github.com/wez/govee-lan-hass/blob/a51376bc736b7bd5d3bf8573169dfefe30dbd9cc/custom_components/govee_lan/light.py#L130

3 seconds is the current timeout.

You could find that `custom_components/govee_lan/light.py` file in your installation and edit that line to increase the timeout, then restart Home Assistant to see if it will be any better.

Note that any local modification you make will be overwritten the next time you update the component via HACS.

**Comment by piedrola** [comment]
Sadly no change. I tried 10, 30 and 120 seconds. 
It doesn't affect the lights. 

In between I tried something else: Did kill internet, did kill bluetooth, just to see if LAN Controls work without any problems. That's the case. So the problem has to be somewhere in HA or your plugin.
If any idea comes to your mind to fix the problem: Let me know. If there is anything you would like me to test: Let me know!   I'd be happy to help.

Thank you 
Daniél

**Comment by GarisonLotus** [comment]
I ran into the same issue. I have an H705A, with HA running in docker. Something going on with the LAN polling. No matter what, it times out - but only when a LAN poll is being attempted. 

I don't have a lot of time to play with this until the weekend, but I did find something interesting... I set line 435 to "True" from False. Now it still times out, but because self._attr_available is set to True, it still allows me to control the light strip as it's still available in HA.  

https://github.com/wez/govee-lan-hass/blob/a51376bc736b7bd5d3bf8573169dfefe30dbd9cc/custom_components/govee_lan/light.py#L435

Also set LAN_POLL_INTERVAL to be 600, so it doesn't even try LAN polling for devices until 10 minutes have past.  

https://github.com/wez/govee-lan-hass/blob/a51376bc736b7bd5d3bf8573169dfefe30dbd9cc/custom_components/govee_lan/light.py#L63

Now it's working.  The above is a 100% a bad bandaid and ignores the problem entirely, but at least it's working until I get more time to play with it. 

This weekend, I'll bust out a PCAP and watch the network traffic to try to get an idea on what is actually going on.  I'm running HA in docker, so there could be something funky with the network traffic.  I did verify that the interfaces light.py appends on line 115 is the correct / single IPV4 IP of the host machine.

**Comment by GarisonLotus** [comment]
ok, I know I said I would wait for the weekend...  but this was bothering me.  So I started digging into it now instead. 

Confirmed via PCAP that traffic was making into the container on port 4003. Confirmed via netstat that port 4003 has a listener on port 4003 on the correct interface. So far, so good. 

Then I enabled the extra logging via the trouble shooting instructions and followed the async calls. Here are my logs, just to make sure I'm reading this right:

> 2023-05-17 17:49:21.665 DEBUG (MainThread) [custom_components.govee_lan.light] async_update will poll 3D:45:D8:33:33:36:31:69 light.permanent_outdoor_lights

ok, so it's going to poll. We knew this worked, otherwise the UDP traffic wouldn't be in the PCAP.

> 2023-05-17 17:49:21.751 DEBUG (MainThread) [govee_led_wez.govee] _lan_poller_process_broadcast msg={'msg': {'cmd': 'scan', 'data': {'ip': '192.168.1.100', 'device': '3D:45:D8:33:33:36:31:69', 'sku': 'H705A', 'bleVersionHard': '3.01.01', 'bleVersionSoft': '1.00.15', 'wifiVersionHard': '1.02.00', 'wifiVersionSoft': '2.05.08'}}} from ('192.168.1.100', 59082)

Looks like the GoveeLanListener and GoveeController classes from govee_led_wez are being called. That's good.  In fact, it processed a reply from the broadcast.  This is the JSON blob response from the device. 

> 2023-05-17 17:49:26.667 DEBUG (MainThread) [custom_components.govee_lan.light] timeout while querying device state for 3D:45:D8:33:33:36:31:69 light.permanent_outdoor_lights
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "/config/custom_components/govee_lan/light.py", line 421, in async_update
>     await self._govee_controller.update_device_state(self._govee_device)
>   File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 287, in update_device_state
>     await asyncio.wait_for(future, timeout=self.device_control_timeout)
>   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
>     raise exceptions.TimeoutError() from exc
> asyncio.exceptions.TimeoutError

So yes, still getting a timeout when trying to update the device state. 

https://github.com/wez/govee-py/blob/main/govee_led_wez/govee.py#L275

Digging into this... I discovered why mine was timing out.  Noticed this in my PCAP:

> src 192.168.1.4 dst 192.168.1.100 {"msg":{"cmd":"devStatus","data":{"onOff":0,"brightness":12,"color":{"r":0,"g":0,"b":0},"colorTemInKelvin":4300}}}

and the reply:

> src 192.168.1.100 dst 192.168.1.4 {"msg":{"cmd":"devStatus","data":{"onOff":0,"brightness":12,"color":{"r":0,"g":0,"b":0},"colorTemInKelvin":4300}}}

... and there it is.  The problem is it's sending out traffic as a different IP then the listener! 

https://github.com/wez/govee-py/blob/main/govee_led_wez/govee.py#L286

Line 286 in govee.py calls "_request_lan_status".  This in turn calls "_send_lan_command" in the same class. 

https://github.com/wez/govee-py/blob/main/govee_led_wez/govee.py#L251

_send_lan_command is using a different interface / IPv4 address (not the one my debugging saw the listener was listening on)  192.168.1.5 is the main IP of my server running docker.  192.168.1.4 is an alternate IP in use by a completely different service (that IP is my plex server). I have no idea why it sent out the request from that IP. 


I'm probably going to stop digging into this tonight.  But I suspect if we might need similar logic around passing in interfaces for the "self._govee_controller.update_device_state" call, like is done when "start_lan_poller" is called.

**Comment by wez** [comment]
Oh interesting! Thanks for digging in!

Yeah, I agree: it sounds like it might be important to set the source address.

I've pushed and published a speculative fix for that. It will only work if the interface list passed to `start_lan_poller` consists of a single interface.

**Comment by GarisonLotus** [comment]
Thanks Wez!  Wanted to confirm that it's working now on my side. 

@piedrola - can you download the latest update via HACS and see if this update has solved your issue and report back? If it works, we can probably close this issue.  Same question for @thomasmandrews

**Comment by piedrola** [comment]
Hey Guys, sorry for being late with my answer. Garison I feel you, I neither could wait to try the changes, but in germany we had a day off (holiday) and I killed the power switch before leaving, I couldn't try it from home.

YOU GUYS DID IT. At least for the last couple of minutes it's all working perfect! Wez update didn't fix my issue, but the changes you mentioned Garison did. 
Thank you guys! 

From my end we can close this issue: If an updates breaks it, I'm know aware of fixing it again for myself! 
~Daniél

**Comment by StarMediaArt** [comment]
Hi, got 2 of H61A5 Light strobes and run into same issues one of the light strobes become unresponsive after restarting HA  within a minute.

`raceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/govee_lan/light.py", line 420, in async_update
    await self._govee_controller.update_device_state(self._govee_device)
  File "/usr/local/lib/python3.11/site-packages/govee_led_wez/govee.py", line 300, in update_device_state
    await asyncio.wait_for(future, timeout=self.device_control_timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
`
changing the LAN_POLL_INTERVAL to 600 and the self._attr_available to True fixed that problem for me, is there any better solution without to change some variables by myself?

**Comment by GarisonLotus** [comment]
@StarMediaArt - do you happen to have multiple interfaces (i.e. eth0, eth1, etc) on the machine you are running this on? If so, my workaround is still the only way to fix that, per Wez. (see: https://github.com/wez/govee-py/blob/main/govee_led_wez/govee.py#L133-L138)

Honestly, I had forgotten about this and I'm glad you reminded me so I could potentially try to help fix it. Maybe I'll hop in to try to fix it in that scenario.

**Comment by StarMediaArt** [comment]
@GarisonLotus  the home assistant runs on a raspberry 3b+, ifconfig tells me only one interface eth0 is on, if that helps. I've added the log before the changes of the values of the poll 

System information
IPv4 addresses for eth0: 192.168.178.79/24
IPv6 addresses for eth0: 2a02:8070:a282:20:30ca:9317:b3d:2550/64, fe80::2e6d:681c:ff99:ab16/64
IPv4 addresses for wlan0:

eth0 Link encap: Ethernet HWaddr 02:42:AC:1E:12:00
inet addr: 172.30.33.0 Bcast:172.30.33.255 Mask: 255.255.254.0
UP BROADCAST RUNNING MULTICAST MTU: 1500 Metric:1
RX packets: 79084 errors:0 dropped:0 overruns:0 frame:0
packets:106 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txaueuelen:0
RX bytes:17928081 (17.0 MiB) TX bytes:185470 (181.1 KiB)
[home-assistant_govee_lan_2023-09-21T09-53-18.139Z.log](https://github.com/wez/govee-lan-hass/files/12693695/home-assistant_govee_lan_2023-09-21T09-53-18.139Z.log)

**Comment by GarisonLotus** [comment]
Thanks for supplying that.  I suspect you are running into the same issue Wez described in his comments when he put a quick fix together for this in May to solve my original issue... but instead of multiple interfaces, you appear to have multiple IPs on a single interface.  The fix in place from May doesn't do a good job when multiple interfaces (or in this case, multiple IPs on ths same interface).

I see two Govee devices in the list in the 192.168.178/24 subnet. It looks like you do have more than one IP (and two subnets) on the same eth0 interface, right?  Running both an IP in 192.168.178/24 and 172.30.33/23.  Curious about that /23, as it's rather large for home use. 

I think the only fix is for us to actually resolve this correctly. My guess (without a PCAP, I can't be sure) is that the polling here is trying to send out as 172.30.33.0/23, not getting a response, thus resulting 

In the meantime, my fix will work and is actually safe to do if you feel comfortable making it manually / locally in your install.

**Comment by wez** [comment]
To fix this right, the underlying python library needs to be told which source address to use, so it needs information about the interface list.  home assistant has that information.  I think either the hass integration needs to compute the source address and pass it down, or needs to pass the list of interfaces down in to the python library and have that compute it.

**Comment by littlej956** [comment]
Hi, sorry to reopen this, i have multiple vlan interfaces on my home assistant instance. I have tried to set  start_lan_poller like this `controller.start_lan_poller("192.168.20.250")` but unfortunately my device gets unavailable after 5 minutes or so. Any idea how to fix this?  Thanks
